---
- name: variables
  hosts: localhost
  vars:
    course: "ansible"
    trainer: "Sivakumar"
    Duration: "150Hrs"
  tasks:
    - name: variables
      ansible.builtin.debug:
        msg: "Hi I am learning {{course}}, from trainer {{trainer}}, and duration is {{Duration}}"
