---
- name: variables
  hosts: localhost
  vars:
    course: "Devops"
    trainer: "siva kumar"
    duration: "150HRS"
  tasks:
    - name: print variables
      ansible.builtin.debug:
        msg: "Hi I am learning course {{course}}, from trainer {{trainer}}, and duration is {{duration}}."
