---
- name: variables
  hosts: localhost
  vars:
    couse: "ansible"
    trainer: "Sivakumar"
    Duration: "150Hrs"
  task:
    - name: variables
      ansible.builtin.debug:
        msg: "Hi I am learning {{course}}, from trainer {{trainer}}, and duration is {{Duration}}"
