---
- name: install nginx and run
  hosts: web
  become: yes
  tasks:
    - name: install nginx
      ansible.builtin.dnf:
        name: nginx
        state: installed
    - name: start service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
