---
- name: variables file
  hosts: localhost
  vars_files:
    - vars.yaml
  tasks:
    - name: variable file overwrite
      ansible.builtin.debug:
        msg: "Hi I am learning course {{course}}, from trainer {{trainer}}, duration is {{duration}}."
