---
- name: Addition of Two Numbers
  hosts: localhost
  vars_prompt:
    - name: "num1"
      prompt: "Please enter the first number"
      private: no
    - name: "num2"
      prompt: "Please enter the second number"
      private: no

  tasks:
    - name: Convert input to integers
      set_fact:
        num1_int: "{{ num1 | int }}"
        num2_int: "{{ num2 | int }}"

    - name: Add the two numbers
      set_fact:
        result: "{{ num1_int + num2_int }}"

    - name: Display the result
      debug:
        msg: "The sum of {{ num1_int }} and {{ num2_int }} is {{ result }}"
