---
- name: Addition of Two Numbers
  hosts: localhost
  gather_facts: no
  vars_prompt:
    - name: "num1"
      prompt: "Please enter the first number"
      private: no
    - name: "num2"
      prompt: "Please enter the second number"
      private: no

  tasks:
    - name: Add the two numbers
      set_fact:
        result: "{{ num1 | int + num2 | int }}"

    - name: Display the result
      ansible.builtin.debug:
        msg: "The sum of {{ num1 }} and {{ num2 }} is {{ result }}"
